// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using ReporterConsole.Data;

namespace ReporterConsole.Migrations
{
    [DbContext(typeof(DefectContext))]
    [Migration("20180409192940_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290");

            modelBuilder.Entity("ReporterConsole.Data.Defect", b =>
                {
                    b.Property<string>("Desc");

                    b.Property<int>("BatchId");

                    b.Property<int>("TaskId");

                    b.Property<string>("DefectNumber");

                    b.HasKey("Desc", "BatchId", "TaskId");

                    b.HasAlternateKey("BatchId", "Desc", "TaskId");

                    b.ToTable("Defects");
                });
#pragma warning restore 612, 618
        }
    }
}
